### ISSUE TITLE
Core elixir: File.stat

### ISSUE THREAD

**Issue by jandudulski** [augiedb/VariousAndSundryCS#2]
I've just read [an article](http://variousandsundry.com/cs/blog/2015/06/24/core-elixir-file-dot-stat/) and found out that there is not the best explanation about error codes:

> - eacces – You don’t have the right access rights (permissions) to that file
> - eperm – Operation Not Permitted (Are you deleting a file you don’t have access to?) 

[As far as I learnt](http://blog.unclesniper.org/archives/2-Linux-programmers,-learn-the-difference-between-EACCES-and-EPERM-already!.html) `eperm` is about allowed operations regardless user permissions so it's not about deleting files which you don't have access - but it could be on a file which - for any reason - cannot be deleted at all.

**Comment by augiedb** [comment]
Interesting.  Thanks for clearing that up for me.  I'm going to edit the original post to clarify that, and include this link, with thanks,
